### ISSUE TITLE
Publish impl support to crates.io

### ISSUE THREAD

**Issue by donkeyteethUX** [Manishearth/rust-adorn#13]
Wondering if the recently added features will be published soon. Impl support would be great.

**Comment by Manishearth** [comment]
Can you make a PR with a version bump? I'll do the rest.

**Comment by donkeyteethUX** [comment]
@Manishearth let me know if this is what you intended

**Comment by Manishearth** [comment]
Yes, it is, I'll merge when I get the chance!
