### ISSUE TITLE
Taking parameters?

### ISSUE THREAD

**Issue by shreevatsa** [Manishearth/rust-adorn#15]
Thanks for this library!

is it possible to pass additional parameters to the decorator, that could be used in its body? (For example, could the `100` in the body of `bar` in the [example in the README](https://github.com/Manishearth/rust-adorn/blob/c5822d6/README.md) be a parameter that's passed in the `#[adorn(bar)]` line?) 

(Python decorators [can take arguments](https://realpython.com/primer-on-python-decorators/#decorators-with-arguments) and they're often useful…)

**Comment by shreevatsa** [comment]
Answering my own question: I tried looking at the source code, and although I don't understand anything about Rust macros, I see it [says](https://github.com/Manishearth/rust-adorn/blob/c5822d6/src/lib.rs#L45):

>         "#[adorn()] takes a single identifier input, followed by optional literal parameters in parentheses"

and it works! Use it something like `#[adorn(bar(100))]` and have `bar` take the parameter after `f` and before the parameters of `f`. Would be good to have an example or two in the documentation, but this is great!

**Comment by Manishearth** [comment]
Happy to accept PRs for docs, I haven't been actively working on adorn for ages
