### ISSUE TITLE
Can't build adorn

### ISSUE THREAD

**Issue by twitu** [Manishearth/rust-adorn#8]
`cargo build` fails when I add adorn to dependencies for version `rustc 1.40.0 (73528e339 2019-12-16)`.

```
   Compiling adorn v0.2.1
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /home/twitu/.cargo/registry/src/github.com-1ecc6299db9ec823/adorn-0.2.1/src/lib.rs:1:1
  |
1 | #![feature(proc_macro)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `adorn`.
```

I notice that you have included `proc-macro = true` in your `.toml` file, do I need to do this as well? I have included my `.toml` below.

```
[package]
name = ""
version = ""
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adorn = "0.2.1"
```

**Comment by Manishearth** [comment]
No, you need to use a nightly compiler.

I suspect this now works on stable but I haven't tried.

**Comment by twitu** [comment]
But the last commit message says that it supports stable rust? It would be great if you can mention something in the README so that a visitor knows which versions/build is supported.

**Comment by Manishearth** [comment]
It's not been published.

**Comment by Manishearth** [comment]
I'll publish soonish

**Comment by Manishearth** [comment]
Done. We really should update the syn/quote deps but it's nontrivial
